// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ingestion/v1/ingestion.proto

package ingestionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionIngestionService_IngestTransaction_FullMethodName = "/ingestion.v1.TransactionIngestionService/IngestTransaction"
)

// TransactionIngestionServiceClient is the client API for TransactionIngestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TransactionIngestionService accepts transaction events on the ingestion
// hot path.
type TransactionIngestionServiceClient interface {
	IngestTransaction(ctx context.Context, in *IngestTransactionRequest, opts ...grpc.CallOption) (*IngestTransactionResponse, error)
}

type transactionIngestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionIngestionServiceClient(cc grpc.ClientConnInterface) TransactionIngestionServiceClient {
	return &transactionIngestionServiceClient{cc}
}

func (c *transactionIngestionServiceClient) IngestTransaction(ctx context.Context, in *IngestTransactionRequest, opts ...grpc.CallOption) (*IngestTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestTransactionResponse)
	err := c.cc.Invoke(ctx, TransactionIngestionService_IngestTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionIngestionServiceServer is the server API for TransactionIngestionService service.
// All implementations must embed UnimplementedTransactionIngestionServiceServer
// for forward compatibility.
//
// TransactionIngestionService accepts transaction events on the ingestion
// hot path.
type TransactionIngestionServiceServer interface {
	IngestTransaction(context.Context, *IngestTransactionRequest) (*IngestTransactionResponse, error)
	mustEmbedUnimplementedTransactionIngestionServiceServer()
}

// UnimplementedTransactionIngestionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionIngestionServiceServer struct{}

func (UnimplementedTransactionIngestionServiceServer) IngestTransaction(context.Context, *IngestTransactionRequest) (*IngestTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestTransaction not implemented")
}
func (UnimplementedTransactionIngestionServiceServer) mustEmbedUnimplementedTransactionIngestionServiceServer() {
}
func (UnimplementedTransactionIngestionServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionIngestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionIngestionServiceServer will
// result in compilation errors.
type UnsafeTransactionIngestionServiceServer interface {
	mustEmbedUnimplementedTransactionIngestionServiceServer()
}

func RegisterTransactionIngestionServiceServer(s grpc.ServiceRegistrar, srv TransactionIngestionServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionIngestionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionIngestionService_ServiceDesc, srv)
}

func _TransactionIngestionService_IngestTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionIngestionServiceServer).IngestTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionIngestionService_IngestTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionIngestionServiceServer).IngestTransaction(ctx, req.(*IngestTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionIngestionService_ServiceDesc is the grpc.ServiceDesc for TransactionIngestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionIngestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ingestion.v1.TransactionIngestionService",
	HandlerType: (*TransactionIngestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestTransaction",
			Handler:    _TransactionIngestionService_IngestTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ingestion/v1/ingestion.proto",
}
