// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ingestion/v1/ingestion.proto

package ingestionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Side identifies the direction of a trade.
type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_ingestion_v1_ingestion_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_ingestion_v1_ingestion_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{0}
}

// TransactionEvent is a transaction event submitted for ingestion.
type TransactionEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EventId    string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TenantId   string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Instrument string                 `protobuf:"bytes,3,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Side       Side                   `protobuf:"varint,4,opt,name=side,proto3,enum=ingestion.v1.Side" json:"side,omitempty"`
	// quantity is a fixed-point decimal scaled by 1e8 (i.e. the real value is
	// quantity / 1e8).
	Quantity int64 `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// price is a fixed-point decimal scaled by 1e8 (i.e. the real value is
	// price / 1e8).
	Price         int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionEvent) Reset() {
	*x = TransactionEvent{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEvent) ProtoMessage() {}

func (x *TransactionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEvent.ProtoReflect.Descriptor instead.
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TransactionEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TransactionEvent) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *TransactionEvent) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *TransactionEvent) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TransactionEvent) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TransactionEvent) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// IngestTransactionRequest wraps a single TransactionEvent for ingestion.
type IngestTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *TransactionEvent      `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestTransactionRequest) Reset() {
	*x = IngestTransactionRequest{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestTransactionRequest) ProtoMessage() {}

func (x *IngestTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestTransactionRequest.ProtoReflect.Descriptor instead.
func (*IngestTransactionRequest) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *IngestTransactionRequest) GetEvent() *TransactionEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// IngestTransactionResponse acknowledges receipt of a TransactionEvent.
type IngestTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestTransactionResponse) Reset() {
	*x = IngestTransactionResponse{}
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestTransactionResponse) ProtoMessage() {}

func (x *IngestTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_v1_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestTransactionResponse.ProtoReflect.Descriptor instead.
func (*IngestTransactionResponse) Descriptor() ([]byte, []int) {
	return file_ingestion_v1_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *IngestTransactionResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *IngestTransactionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_ingestion_v1_ingestion_proto protoreflect.FileDescriptor

const file_ingestion_v1_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x1cingestion/v1/ingestion.proto\x12\fingestion.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x02\n" +
	"\x10TransactionEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1e\n" +
	"\n" +
	"instrument\x18\x03 \x01(\tR\n" +
	"instrument\x12&\n" +
	"\x04side\x18\x04 \x01(\x0e2\x12.ingestion.v1.SideR\x04side\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12;\n" +
	"\voccurred_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"P\n" +
	"\x18IngestTransactionRequest\x124\n" +
	"\x05event\x18\x01 \x01(\v2\x1e.ingestion.v1.TransactionEventR\x05event\"R\n" +
	"\x19IngestTransactionResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted*9\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x022\x83\x01\n" +
	"\x1bTransactionIngestionService\x12d\n" +
	"\x11IngestTransaction\x12&.ingestion.v1.IngestTransactionRequest\x1a'.ingestion.v1.IngestTransactionResponseB\\ZZgithub.com/anwinsenp/go-transaction-control-plane/internal/api/pb/ingestion/v1;ingestionv1b\x06proto3"

var (
	file_ingestion_v1_ingestion_proto_rawDescOnce sync.Once
	file_ingestion_v1_ingestion_proto_rawDescData []byte
)

func file_ingestion_v1_ingestion_proto_rawDescGZIP() []byte {
	file_ingestion_v1_ingestion_proto_rawDescOnce.Do(func() {
		file_ingestion_v1_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestion_v1_ingestion_proto_rawDesc), len(file_ingestion_v1_ingestion_proto_rawDesc)))
	})
	return file_ingestion_v1_ingestion_proto_rawDescData
}

var file_ingestion_v1_ingestion_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ingestion_v1_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ingestion_v1_ingestion_proto_goTypes = []any{
	(Side)(0),                         // 0: ingestion.v1.Side
	(*TransactionEvent)(nil),          // 1: ingestion.v1.TransactionEvent
	(*IngestTransactionRequest)(nil),  // 2: ingestion.v1.IngestTransactionRequest
	(*IngestTransactionResponse)(nil), // 3: ingestion.v1.IngestTransactionResponse
	(*timestamppb.Timestamp)(nil),     // 4: google.protobuf.Timestamp
}
var file_ingestion_v1_ingestion_proto_depIdxs = []int32{
	0, // 0: ingestion.v1.TransactionEvent.side:type_name -> ingestion.v1.Side
	4, // 1: ingestion.v1.TransactionEvent.occurred_at:type_name -> google.protobuf.Timestamp
	1, // 2: ingestion.v1.IngestTransactionRequest.event:type_name -> ingestion.v1.TransactionEvent
	2, // 3: ingestion.v1.TransactionIngestionService.IngestTransaction:input_type -> ingestion.v1.IngestTransactionRequest
	3, // 4: ingestion.v1.TransactionIngestionService.IngestTransaction:output_type -> ingestion.v1.IngestTransactionResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ingestion_v1_ingestion_proto_init() }
func file_ingestion_v1_ingestion_proto_init() {
	if File_ingestion_v1_ingestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestion_v1_ingestion_proto_rawDesc), len(file_ingestion_v1_ingestion_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingestion_v1_ingestion_proto_goTypes,
		DependencyIndexes: file_ingestion_v1_ingestion_proto_depIdxs,
		EnumInfos:         file_ingestion_v1_ingestion_proto_enumTypes,
		MessageInfos:      file_ingestion_v1_ingestion_proto_msgTypes,
	}.Build()
	File_ingestion_v1_ingestion_proto = out.File
	file_ingestion_v1_ingestion_proto_goTypes = nil
	file_ingestion_v1_ingestion_proto_depIdxs = nil
}
